CREATE TABLE if not exists [logs](
    [DateTime] [datetime] NULL,
    [FileName] [char](200) NULL,
    [Moment] [char](12) NULL,
    [Duration] [numeric](18, 5) NULL,
    [EventName] [char](15) NULL,
    [Process] [char](50) NULL,
    [Level] [char](3) NULL,
    [ProcessName] [char](50) NULL,
    [text] [varchar](500) NULL,
    [EventNumber] [int] NULL,
    [t_clientID] [char](10) NULL,
    [t_applicationName] [char](50) NULL,
    [t_computerName] [char](50) NULL,
    [t_connectID] [char](10) NULL,
    [SessionID] [char](10) NULL,
    [Usr] [char](100) NULL,
    [AppID] [char](20) NULL,
    [dbpid] [char](10) NULL,
    [Sql] [varchar](500) NULL,
    [TablesList] [varchar](500) NULL,
    [Prm] [varchar](500) NULL,
    [ILev] [char](20) NULL,
    [Rows] [char](10) NULL,
    [Context] [varchar](500) NULL,
    [ContextLastRow] [varchar](500) NULL,
    [Func] [char](50) NULL,
    [Trans] [char](1) NULL,
    [RowsAffected] [char](10) NULL,
    [Descr] [varchar](500) NULL,
    [planSQLText] [varchar](500) NULL,
    [Exception] [char](100) NULL
    )
